# Generated by Django 4.0.2 on 2022-09-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquityThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOIPercentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOITotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveEquityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(default='', max_length=20)),
                ('open', models.CharField(default='', max_length=20)),
                ('high', models.CharField(default='', max_length=20)),
                ('low', models.CharField(default='', max_length=20)),
                ('prev_day_close', models.CharField(default='', max_length=20)),
                ('ltp', models.CharField(max_length=20)),
                ('strike', models.CharField(max_length=20)),
                ('opencrossed', models.CharField(default='', max_length=20)),
                ('section', models.IntegerField(default=0)),
                ('difference', models.CharField(default='', max_length=10)),
                ('change_perc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LiveOIChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LiveOIPercentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('strikegap', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiveOITotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('strikegap', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiveOITotalAllSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('call1', models.CharField(default='', max_length=20)),
                ('call2', models.CharField(default='', max_length=20)),
                ('put1', models.CharField(default='', max_length=20)),
                ('put2', models.CharField(default='', max_length=20)),
                ('callstrike', models.CharField(max_length=20)),
                ('putstrike', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=20)),
                ('expiry', models.DateField()),
                ('callone', models.CharField(default='', max_length=20)),
                ('putone', models.CharField(default='', max_length=20)),
                ('callhalf', models.CharField(default='', max_length=20)),
                ('puthalf', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('change_perc', models.FloatField(default=0)),
                ('doneToday', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SuperLiveSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('change_perc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TestEquityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateTimeField()),
                ('symbol', models.CharField(default='', max_length=20)),
                ('open', models.CharField(default='', max_length=20)),
                ('high', models.CharField(default='', max_length=20)),
                ('low', models.CharField(default='', max_length=20)),
                ('prev_day_close', models.CharField(default='', max_length=20)),
                ('ltp', models.CharField(max_length=20)),
                ('strike', models.CharField(max_length=20)),
                ('opencrossed', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
