# Generated by Django 4.0.2 on 2022-09-06 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitythree',
            name='change_perc',
            field=models.FloatField(default=0),
        ),
    ]
