# Generated by Django 4.0.2 on 2022-09-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equitythree_change_perc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuperLiveSegment',
        ),
    ]
