# Generated by Django 4.0.2 on 2022-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_superlivesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperLiveSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('change_perc', models.FloatField(default=1)),
            ],
        ),
    ]
