# Generated by Django 3.2.12 on 2022-11-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_superlivesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveequityresult',
            name='below_three',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
