# Generated by Django 3.2.16 on 2022-11-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_liveequityresult_below_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveoichange',
            name='call_ceoi_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='call_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='call_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='max_ceoi_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='put_ceoi_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='put_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='put_max_ceoi_strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveoichange',
            name='put_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
